resources:
- name: newest
  type: git
  source:
    uri: git@gitlab.com:multikatt/newest.git
    branch: master
    private_key: {{ssh_key}}

jobs:
- name: newest
  plan:
  - get: newest
    trigger: true
  - task: tests
    file: newest/build.yml
